"""
Django settings for helloworld_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vlpv1ciy1_f(*@&wt+(zsj&@qs_f%#3ew*f*j^#!+wl(sd8yns'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ------------------------------------------------------------
# Docker note:
# When running Django inside Docker, requests may come from
# different hostnames (e.g. localhost, container name, etc.).
# Using ["*"] avoids host blocking issues in a demo / learning
# environment and allows the app to run without extra setup.
#
# WARNING: This is NOT recommended for production use.
# ------------------------------------------------------------
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages',  # app agregada
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'helloworld_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'helloworld_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ------------------------------------------------------------
# Docker note (SQLite persistence):
# Docker containers are ephemeral, meaning files stored inside
# the container filesystem can be lost when the container is
# recreated.
#
# To ensure SQLite data persists across container restarts,
# the database file is stored under BASE_DIR / 'data', which
# is mounted as a Docker volume via docker-compose.yml.
# ------------------------------------------------------------
SQLITE_DIR = BASE_DIR / 'data'
SQLITE_DIR.mkdir(exist_ok=True)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ------------------------------------------------------------
# Media files (imagenes subidas por el usuario)
# MEDIA_URL: prefijo de la URL publica para acceder a los archivos
# MEDIA_ROOT: carpeta en el servidor donde se guardan fisicamente
# ------------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ------------------------------------------------------------
# Service Provider para el almacenamiento de imagenes (DIP)
# Permite cambiar la implementacion concreta sin tocar las vistas.
# Para usar otro storage (e.g. S3), solo cambia esta linea.
# ------------------------------------------------------------
IMAGE_STORAGE_CLASS = 'pages.utils.ImageLocalStorage'